variables:
    docker_image: ${REGISTRY_URL}/${REGISTRY_PROJECT_NAME}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
    docker_container: ${CI_PROJECT_NAME}
stages:
    - buildandpush
    - deploy
    - checklog

buildandpush:
    stage: buildandpush
    before_script:
        - docker login ${REGISTRY_URL} -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
    script:
        - docker build -t $docker_image .
        - docker push $docker_image 
    tags:
        - dev-server
    only:
        - tags
deploy:
    stage: deploy
    before_script:
        - docker login ${REGISTRY_URL} -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
    script:
        - docker pull $docker_image
        - docker rm -f $docker_container
        - docker run --name $docker_container -dp 8085:8080 $docker_image
    tags:
        - dev-server
    only:
        - tags

checklog:
    stage: checklog
    script:
        - sleep 20 
        - docker logs $docker_container
    tags:
        - dev-server
    only:
        - tags


