variables:
    projectname: shoe-ShoppingCart
    projectuser: shoeshop
    version: 0.0.1-SNAPSHOT
    projectpath: /data/$projectuser

stages:
    - build
    - deploy
    - checklog

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - mvn install -DskipTests=true
    tags:
        - dev-server
    only:
        - tags
deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - sudo cp target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar $projectpath
        - sudo chown -R $projectuser:$projectuser $projectpath
        - sudo chmod -R 755 $projectpath
        - sudo su $projectuser -c "kill -9 $(ps -ef|grep shoe-ShoppingCart-0.0.1-SNAPSHOT.jar|grep -v grep|awk '{print $2}') || true"
        - sudo su $projectuser -c "cd $projectpath; nohup java -jar shoe-ShoppingCart-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &"
    tags:
        - dev-server
    only:
        - tags

checklog:
    stage: checklog
    variables:
        GIT_STRATEGY: none
    script:
        - sleep 20 
        - sudo su $projectuser -c "cd $projectpath; tail -n 10000 nohup.out"
    tags:
        - dev-server
    only:
        - tags


